version: "3"

services:

  redis:
    image: redis:alpine
    hostname: redis
    volumes:
      - ./data/redis:/data

  resque-web:
    image: ennexa/resque-web
    hostname: resque-web
    command: '-r redis://redis:6379'
    depends_on:
      - redis
    ports:
      - "5678:5678"

  front-app:
    image: front-app:latest
    hostname: front-app
    build: ./front-app
    depends_on:
      - redis
    ports:
      - "3000:3000"

  worker:
    image: worker:latest
    hostname: worker
    build: ./worker
    depends_on:
      - redis
